# my-go-demo-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - name: http-metrics  # ✅ 添加端口名称
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}